export const CompaniesData = [
  {
    companyId: 1,
    organisationId: 1,
    countryId: "1",
    company: "ABC Corporation",
    description: "A leading technology company",
    logo: "",
    url: "https://www.abc-corp.com",
    address: "123 Main Street",
    country: "USA",
    zipCode: "12345",
    cin: "CIN123456",
    phone: "+1 (555) 123-4567",
    email: "info@abc-corp.com",
    isActive: "1",
    createdBy: "Admin",
    createdOn: "2023-12-01",
    modifiedBy: null,
    modifiedOn: null,
  },
  {
    companyId: 2,
    organisationId: 1,
    countryId: "2",
    company: "XYZ Ltd",
    description: "Global manufacturing company",
    logo: "",
    url: "https://www.xyz-ltd.com",
    address: "456 Industrial Avenue",
    country: "UK",
    zipCode: "SW1A 1AA",
    cin: "CIN654321",
    phone: "+44 20 1234 5678",
    email: "info@xyz-ltd.com",
    isActive: "0",
    createdBy: "Admin",
    createdOn: "2023-12-02",
    modifiedBy: null,
    modifiedOn: null,
  },
  {
    companyId: 3,
    organisationId: 1,
    countryId: "3",
    company: "Tech Innovators Inc.",
    description: "Innovating technology solutions",
    logo: "",
    url: "https://www.tech-innovators.com",
    address: "789 Tech Boulevard",
    country: "Germany",
    zipCode: "54321",
    cin: "CIN789012",
    phone: "+49 123 456 7890",
    email: "info@tech-innovators.com",
    isActive: "1",
    createdBy: "Admin",
    createdOn: "2023-12-03",
    modifiedBy: null,
    modifiedOn: null,
  },
  {
    companyId: 4,
    organisationId: 1,
    countryId: "4",
    company: "Global Logistics Co.",
    description: "Your trusted logistics partner",
    logo: "",
    url: "https://www.global-logistics.com",
    address: "321 Logistics Avenue",
    country: "China",
    zipCode: "100000",
    cin: "CIN456789",
    phone: "+86 10 8765 4321",
    email: "info@global-logistics.com",
    isActive: "1",
    createdBy: "Admin",
    createdOn: "2023-12-04",
    modifiedBy: null,
    modifiedOn: null,
  },
  {
    companyId: 5,
    organisationId: 1,
    countryId: "5",
    company: "Infinite Innovations",
    description: "Unleashing infinite possibilities",
    logo: "",
    url: "https://www.infinite-innovations.com",
    address: "567 Innovation Street",
    country: "Japan",
    zipCode: "98765",
    cin: "CIN901234",
    phone: "+81 3 9876 5432",
    email: "info@infinite-innovations.com",
    isActive: "0",
    createdBy: "Admin",
    createdOn: "2023-12-05",
    modifiedBy: null,
    modifiedOn: null,
  },
  {
    companyId: 6,
    organisationId: 1,
    countryId: "6",
    company: "SolarTech Solutions",
    description: "Harnessing the power of the sun",
    logo: "",
    url: "https://www.solartech-solutions.com",
    address: "876 Solar Street",
    country: "Australia",
    zipCode: "2000",
    cin: "CIN345678",
    phone: "+61 2 8765 4321",
    email: "info@solartech-solutions.com",
    isActive: "1",
    createdBy: "Admin",
    createdOn: "2023-12-06",
    modifiedBy: null,
    modifiedOn: null,
  },
];

export const employeeDetails = {
  employeeId: "EMP001",
  firstName: "Khadija",
  lastName: "Ahmed",
  dateOfBirth: "1990-01-15",
  gender: "female",
  religion: "Muslim",
  bloodGroup: "A+",
  isActive: true,
  joiningDate: "14-03-1989",
  maritalStatus: "Married",
  imgurl: "",
  contactDetails: {
    email: "khadija@loyaltri.com",
    phone: "+971 50521252",
    address: "123 Main St, Cityville",
    postalCode: "12345",
  },
  country: "United States",
  addressType: "Residential",
  city: "Cityville",
  state: "CA",
  workDetails: {
    company: "XYZ Corp",
    departmentId: "DEV001",
    department: "Development",
    workRole: "Project Manager",
    workTiming: "General Shift (9:00 to 18:00)",
    manager: "Jane Smith",
    joiningDate: "2022-01-01",
    designationId: 4,
    shiftSchemeId: "SHIFT001",
    category: "IT",
  },
  profileCompletion: 80,
};


